# Generated by Django 6.0.1 on 2026-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('purpose', models.CharField(max_length=200)),
                ('visit_to', models.CharField(max_length=100)),
                ('hostel_or_office', models.CharField(max_length=100)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=5)),
            ],
        ),
    ]
