# Generated by Django 6.0.1 on 2026-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/'),
        ),
    ]
