# Generated by Django 6.0.1 on 2026-01-22 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='aadhaar',
            field=models.CharField(default='000000000000', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='aadhaar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_cards/'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='address',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='signature',
            field=models.ImageField(default='signatures/default.png', upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='hostel_or_office',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
