# Generated by Django 6.0.1 on 2026-01-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitor_aadhaar_visitor_aadhaar_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='hostel_name',
            field=models.CharField(default='Not Assigned', max_length=100),
            preserve_default=False,
        ),
    ]
