# Generated by Django 6.0.1 on 2026-01-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_visitor_hostel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='aadhaar_photo',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='hostel_name',
        ),
    ]
