# Generated by Django 6.0.1 on 2026-02-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_employee_employeeattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_in_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_out_time',
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Staff', max_length=100),
        ),
    ]
